no.nav.security.oidc:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
    acceptedaudience: ${ACCEPTEDAUDIENCE} #Ligger i vault
    cookie_name: selvbetjening-idtoken

SOKNAD_KONTANTSTOTTE_SAK_API_URL: http://familie-ks-sak.nais.preprod.local/api
STS_URL: http://security-token-service.default.svc.nais.local