server:
  servlet:
    context-path: /

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main.banner-mode: "off"
  datasource:
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: true

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "status/isAlive"
  metrics.export.prometheus.enabled: true
  metrics.web.server.auto-time-requests: true

http.proxy: http://webproxy-nais.nav.no:8088
STS_URL: http://security-token-service.default.svc.nais.local

CREDENTIAL_USERNAME: INVALID_USERNAME
CREDENTIAL_PASSWORD: INVALID_PASSWORD
