no.nav.security.oidc:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken

SOKNAD_KONTANTSTOTTE_SAK_API_URL: http://localhost:8083