no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
    acceptedaudience: ${ACCEPTEDAUDIENCE} #Ligger i vault
    cookie_name: selvbetjening-idtoken
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${KS_MOTTAK_FRONTEND_CLIENT_ID}
    proxyurl: http://webproxy-nais.nav.no:8088
    cookie_name: azure_token

AAD_URL: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token

spring:
  datasource:
    url: jdbc:postgresql://b27dbvl008.preprod.local:5432/familie-ks-mottak

