no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken
  issuer.azuread:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql=false
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false

logging:
  config: "classpath:logback-test.xml"

FAMILIE_KS_SAK_API_URL: http://localhost:8083/api
FAMILIE_KS_OPPSLAG_API_URL: http://localhost:8085/api

#Brukes til tilgangskontroll av familie-ks-mottak-frontend
MOTTAK_ROLLE: ROLE_GI_MEG_TILGANG

server:
  port: 8084
