no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken
  issuer.azuread:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken
  client:
    registration:
      ks-sak-onbehalfof:
        resource-url: ""
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${KS_SAK_SCOPE}
        authentication:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      ks-oppslag-clientcredentials:
        resource-url: ""
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${KS_OPPSLAG_SCOPE}
        authentication:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql=false
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false

logging:
  config: "classpath:logback-test.xml"

FAMILIE_KS_SAK_API_URL: http://localhost:8083/api
FAMILIE_KS_OPPSLAG_API_URL: http://localhost:8085/api

server:
  port: 8084
