no.nav.security.oidc:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
    acceptedaudience: ${ACCEPTEDAUDIENCE} #Ligger i vault
    cookie_name: selvbetjening-idtoken

spring:
  datasource:
    url: jdbc:postgresql://b27dbvl008.preprod.local:5432/familie-ks-mottak


SOKNAD_KONTANTSTOTTE_SAK_API_URL: http://familie-ks-sak/api
