no.nav.security.oidc:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
    acceptedaudience: ${ACCEPTEDAUDIENCE} #Ligger i vault
    cookie_name: selvbetjening_idtoken

spring:
  datasource:
    url: jdbc:postgresql://b27dbvl007.prod.local:5432/familie-ks-mottak

# Appdynamics
APPDYNAMICS_CONTROLLER_HOST_NAME: appdynamics.adeo.no
APPDYNAMICS_CONTROLLER_PORT: 443
APPDYNAMICS_CONTROLLER_SSL_ENABLED: true
APPDYNAMICS_AGENT_ACCOUNT_NAME: PROD

SOKNAD_KONTANTSTOTTE_SAK_API_URL: http://familie-ks-sak/api

