no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: http://vtp:8060/rest/isso/oauth2/.well-known/openid-configuration
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken
  issuer.azuread:
    discoveryurl: http://vtp:8060/rest/isso/oauth2/.well-known/openid-configuration
    accepted_audience: dummy
    cookie_name: azure_token
  client:
    registration:
      ks-sak-clientcredentials:
        resource-url: ${FAMILIE_KS_SAK_API_URL}
        token-endpoint-url: http://vtp:8060/rest/isso/oauth2/access_token
        grant-type: client_credentials
        scope: dummy
        authentication:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      ks-oppslag-clientcredentials:
        resource-url: ${FAMILIE_KS_OPPSLAG_API_URL}
        token-endpoint-url: http://vtp:8060/rest/isso/oauth2/access_token
        grant-type: client_credentials
        scope: dummy
        authentication:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic

spring:
  datasource:
    url: jdbc:postgresql://postgres-mottak:5432/familieksmottak
    hikari:
      username: familie
      password: familie-pwd
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql=false
    hibernate:
      ddl-auto: create
  flyway:
    enabled: true

logging:
  config: "classpath:logback-spring.xml"

FAMILIE_KS_SAK_API_URL: http://familie-ks-sak:8083/api
FAMILIE_KS_OPPSLAG_API_URL: http://familie-ks-oppslag:8085/api

CLIENT_ID: ""
CLIENT_SECRET: ""

#Brukes til tilgangskontroll av familie-ks-mottak-frontend
MOTTAK_ROLLE: group1

server:
  port: 8084
