no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: http://localhost:8080/metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${CLIENT_ID}
    cookie_name: azure_token
  client:
    registration:
      ks-sak-clientcredentials:
        resource-url: ${FAMILIE_KS_SAK_API_URL}
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${KS_SAK_SCOPE}
        authentication:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      ks-oppslag-clientcredentials:
        resource-url: ${FAMILIE_KS_OPPSLAG_API_URL}
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${KS_OPPSLAG_SCOPE}
        authentication:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql=false
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false

logging:
  config: "classpath:logback-test.xml"

FAMILIE_KS_SAK_API_URL: http://localhost:8083/api
FAMILIE_KS_OPPSLAG_API_URL: http://localhost:8085/api

#Brukes til tilgangskontroll av familie-ks-mottak-frontend
MOTTAK_ROLLE: group1

server:
  port: 8084
