ALTER TABLE HENVENDELSE RENAME TO TASK;
ALTER TABLE HENVENDELSE_LOGG RENAME TO TASK_LOGG;

ALTER TABLE TASK ADD COLUMN type varchar(100);
UPDATE TASK SET type = 'sendSøknadTilSak';
ALTER TABLE TASK ALTER COLUMN type set not null;

ALTER TABLE TASK_LOGG ADD COLUMN feilmelding text;
