ALTER TABLE HENVENDELSE
    ALTER COLUMN id SET DATA TYPE bigint;
ALTER TABLE HENVENDELSE
    ALTER COLUMN id DROP default;

DROP SEQUENCE henvendelse_id_seq CASCADE;
CREATE SEQUENCE HENVENDELSE_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;

ALTER TABLE HENVENDELSE_LOGG
    ALTER COLUMN id SET DATA TYPE bigint;
ALTER TABLE HENVENDELSE_LOGG
    ALTER COLUMN id DROP default;

DROP SEQUENCE henvendelse_logg_id_seq CASCADE ;

CREATE SEQUENCE HENVENDELSE_LOGG_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;