ALTER TABLE HENVENDELSE
    ALTER COLUMN id SET DATA TYPE bigint;

DROP SEQUENCE henvendelse_id_seq;
CREATE SEQUENCE HENVENDELSE_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;

ALTER TABLE HENVENDELSE_LOGG
    ALTER COLUMN id SET DATA TYPE bigint;

DROP SEQUENCE henvendelse_logg_id_seq;

CREATE SEQUENCE HENVENDELSE_LOGG_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;