ALTER TABLE HENVENDELSE
    RENAME TO TASK;
ALTER TABLE HENVENDELSE_LOGG
    RENAME TO TASK_LOGG;

ALTER TABLE TASK
    ADD COLUMN type varchar(100);
UPDATE TASK
SET type = 'sendSøknadTilSak';
ALTER TABLE TASK
    ALTER COLUMN type set not null;

ALTER TABLE TASK_LOGG
    ADD COLUMN feilmelding text;
ALTER TABLE TASK_LOGG
    rename COLUMN henvendelse_id to task_id;

ALTER SEQUENCE henvendelse_seq RENAME TO task_seq;
ALTER SEQUENCE henvendelse_logg_seq RENAME TO task_logg_seq;

UPDATE TASK
SET status = 'AVVIKS_HÅNDTERT'
WHERE status = 'FEILET';

ALTER TABLE TASK
    ADD COLUMN metadata VARCHAR(4000);
